### ISSUE TITLE
gmp.h not found

### ISSUE THREAD

**Issue by khanzf** [mozilla/browserid-verifier#105]
Hi,
I am trying to compile this on FreeBSD. I am getting an error reporting that gmp.h is not found. FreeBSD stores this file in /usr/local/include/gmp.h. Where would I modify the include path to include /usr/local/include?
Thanks

**Comment by rfk** [comment]
Thanks for the report.  I expect this error is coming from one of the dependencies, could you please post the build output with the error to help track it down?

**Comment by rfk** [comment]
Great, thanks!  It looks l like this is a build failure in the optional `bigint` dependency.  If you ignore the build failure and try to run things anyway, does it appear to work?

(I'll see if there's a way to pass extra include directories to get it compiling, but it's useful to know if this is a blocker or an annoyance from your PoV)

**Comment by rfk** [comment]
I'm also not sure why it's building `bigint`, on my system it builds `bignum` instead, which depends on openssl rather than libgmp.

**Comment by rfk** [comment]
> FreeBSD stores this file in /usr/local/include/gmp.h. Where would I modify the include path
> to include /usr/local/include?

I had a look but can't see any obvious way to do this :-(

**Comment by khanzf** [comment]
How do I check if it's working?

And, where does the compile command "come from"? I'm not the most versed in
node.

**Comment by rfk** [comment]
> How do I check if it's working?

Doing `npm test` should run without errors.

> And, where does the compile command "come from"? 

Doing `npm install invokes some sort of native-module-building tool called `node-gyp` but I don't know enough about it to know how to pass config options down into that build process.

**Comment by khanzf** [comment]
Quite a few errors below.

```
[farhan@workbench ~/fxa-local-dev/browserid-verifier]$ npm test

> browserid-verifier@0.8.0 test /usr/home/farhan/fxa-local-dev/browserid-verifier
> mocha -t 5000 -R spec tests/*.js



(node:51934) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
  audience tests
    ✓ test servers should start (697ms)
    ✓ test assertion should be created
    1) should verify with complete audience
    2) should fail to verify with different domain as audience
    3) should fail to verify with different port
    4) should fail to verify with incorrect scheme
    ✓ should fail to verify if audience is missing
    ✓ test servers should stop

  basic verifier test
    ✓ test servers should start (654ms)
    5) should verify an assertion
    ✓ should return 405 for GET requests
    ✓ should handle any errors
    ✓ test servers should stop

  cascading configuration files
    ✓ create a couple configuration files
    ✓ test servers should start (376ms)
    ✓ test servers should shutdown cleanly
    ✓ verifier should have determined proper configuration

  content-type tests
    ✓ test servers should start (559ms)
    ✓ test assertion should be created
    ✓ (v2 api) should fail to verify when content-type is unsupported
    ✓ (v2 api) should fail to verify when content-type is not specified
    ✓ (v1 api) should fail to verify when content-type is unsupported
    ✓ (v1 api) should fail to verify when content-type is not specified
    ✓ (v2 api) shouldn't get confused when extended content-types are used
    ✓ (v1 api) shouldn't get confused when extended content-types are used
    ✓ (v2 api) shouldn't support x-www-form-urlencoded
    ✓ (v1 api) should support x-www-form-urlencoded
    ✓ test servers should stop

  fallback configuration test
    ✓ test servers should start (594ms)
    6) should verify an assertion vouched by the configured fallback
    ✓ verifier should restart with cleared fallback (375ms)
    7) should fail to verify an assertion when fallback is not configured
    ✓ test servers should stop

  force issuer
    ✓ test idps should start up (849ms)
    8) assertion by fallback when primary support is present should fail
    9) (v1) forceIssuer should over-ride authority discovery
    10) (v2) trustedIssuers should over-ride authority discovery
    ✓ test idp should shut down

  health check
    ✓ test server should start (371ms)
    ✓ health check should return OK
    ✓ test server should stop

  source code syntax
    ✓ .jshintrc should be readable
    ✓ we should be able to discover files to lint
    ✓ syntax checking should yield no errors (194ms)

  custom log formatter
    ✓ should successfully process log messages

  missing assertion test
    ✓ test servers should start (365ms)
    ✓ should fail to verify when assertion is missing
    ✓ test servers should stop

  audience tests
    ✓ test servers should start (536ms)
    ✓ test assertion should be created
    ✓ (v1 api) should return a 503 on service failure (123ms)
    ✓ (v2 api) should return a 503 on service failure
    ✓ test servers should stop

  audience tests
    ✓ test servers should start (660ms)
    ✓ test assertion should be created
    11) should verify when trusted issuers is specified
    ✓ should fail when trusted issuers is not specified
    ✓ should fail when trusted issuers is not an array
    ✓ should fail when trusted issuers contains non-strings
    ✓ test servers should stop

  unverified email
    ✓ test idps should start up (431ms)
    12) (v1) assertion with unverified email address should fail to verify
    13) (v1) assertion with unverified email address and forceIssuer should verify
    14) (v1) allowUnverified causes extraction of unverified email addresses
    ✓ test idp should shut down

  code coverage
    15) tests should exceed 95% coverage
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:51934) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    ✓ coverage.html should be written (179ms)


  52 passing (8s)
  15 failing

  1) audience tests should verify with complete audience:

      Uncaught AssertionError: expected 'okay' to be 'failure'
      + expected - actual

      -okay
      +failure
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/audience.js:53:23)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  2) audience tests should fail to verify with different domain as audience:

      Uncaught AssertionError: expected '127.0.0.1:54798 is not a browserid primary: Error: socket hang up' to be 'audience mismatch: domain mismatch'
      + expected - actual

      -127.0.0.1:54798 is not a browserid primary: Error: socket hang up
      +audience mismatch: domain mismatch
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/audience.js:63:30)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  3) audience tests should fail to verify with different port:

      Uncaught AssertionError: expected '127.0.0.1:54798 is not a browserid primary: Error: socket hang up' to be 'audience mismatch: port mismatch'
      + expected - actual

      -127.0.0.1:54798 is not a browserid primary: Error: socket hang up
      +audience mismatch: port mismatch
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/audience.js:73:30)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  4) audience tests should fail to verify with incorrect scheme:

      Uncaught AssertionError: expected '127.0.0.1:54798 is not a browserid primary: Error: socket hang up' to be 'audience mismatch: scheme mismatch'
      + expected - actual

      -127.0.0.1:54798 is not a browserid primary: Error: socket hang up
      +audience mismatch: scheme mismatch
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/audience.js:83:30)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  5) basic verifier test should verify an assertion:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at Request._callback (tests/basic.js:44:24)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  6) fallback configuration test should verify an assertion vouched by the configured fallback:

      Uncaught AssertionError: expected 'failure' to be 'okay'
      + expected - actual

      -failure
      +okay
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/fallback.js:48:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  7) fallback configuration test should fail to verify an assertion when fallback is not configured:
     Uncaught AssertionError: expected '127.0.0.1:29425 is not a browserid primary: Error: socket hang up' to start with 'untrusted issuer'
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value [as startWith] (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/fallback.js:91:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  8) force issuer assertion by fallback when primary support is present should fail:
     Uncaught AssertionError: expected '127.0.0.1:29433 is not a browserid primary: Error: socket hang up' to start with 'untrusted issuer'
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value [as startWith] (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/force-issuer.js:53:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  9) force issuer (v1) forceIssuer should over-ride authority discovery:

      Uncaught AssertionError: expected 'failure' to be 'okay'
      + expected - actual

      -failure
      +okay
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/force-issuer.js:80:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  10) force issuer (v2) trustedIssuers should over-ride authority discovery:

      Uncaught AssertionError: expected 'failure' to be 'okay'
      + expected - actual

      -failure
      +okay
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/force-issuer.js:107:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  11) audience tests should verify when trusted issuers is specified:

      Uncaught AssertionError: expected 'okay' to be 'failure'
      + expected - actual

      -okay
      +failure
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/trusted-issuers.js:59:23)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  12) unverified email (v1) assertion with unverified email address should fail to verify:
     Uncaught AssertionError: expected '127.0.0.1:29463 is not a browserid primary: Error: socket hang up' to start with 'untrusted assertion'
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value [as startWith] (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/unverified-email.js:49:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  13) unverified email (v1) assertion with unverified email address and forceIssuer should verify:

      Uncaught AssertionError: expected 'failure' to be 'okay'
      + expected - actual

      -failure
      +okay
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/unverified-email.js:73:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  14) unverified email (v1) allowUnverified causes extraction of unverified email addresses:

      Uncaught AssertionError: expected 'failure' to be 'okay'
      + expected - actual

      -failure
      +okay
      
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/unverified-email.js:102:32)
      at Request.self.callback (node_modules/request/request.js:187:22)
      at Request.<anonymous> (node_modules/request/request.js:1048:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:969:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  15) code coverage tests should exceed 95% coverage:
     Uncaught AssertionError: expected '91.8' to be above 95
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at tests/zzz-report-coverage.js:19:31
      at node_modules/ass/index.js:133:9
      at module.exports (node_modules/ass/lib/reporters/json.js:19:3)
      at node_modules/ass/index.js:132:7
      at node_modules/ass/index.js:123:9
      at Array.forEach (<anonymous>)
      at node_modules/ass/index.js:122:17
      at FSReqWrap.oncomplete (fs.js:153:20)



npm ERR! Test failed.  See above for more details.
```

**Comment by khanzf** [comment]
This is a problem with node-bigint, not browserid-verifier.
Closing issue and opening a ticket there.
